<a href="https://colab.research.google.com/github/genpaku-ng0220/Prog2_11th/blob/main/work1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandasライブラリを使って, 今季の広島東洋カープの1軍投手成績を分析するプログラムを作る.

In [1]:
!wget "https://drive.google.com/uc?export=download&id=11LfmYHZBtwKLdaG39Vj29VJJCGLB6xn-" -O carp_2022.csv

--2022-12-22 08:26:22--  https://drive.google.com/uc?export=download&id=11LfmYHZBtwKLdaG39Vj29VJJCGLB6xn-
Resolving drive.google.com (drive.google.com)... 74.125.124.102, 74.125.124.100, 74.125.124.138, ...
Connecting to drive.google.com (drive.google.com)|74.125.124.102|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-0s-7k-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/gdgc9922pgc9sfe0n85c5shuv5dli9km/1671697575000/07254241957354570833/*/11LfmYHZBtwKLdaG39Vj29VJJCGLB6xn-?e=download&uuid=bb195c8f-8a1b-49fe-9d37-531549aca139 [following]
Warning: wildcards not supported in HTTP.
--2022-12-22 08:26:22--  https://doc-0s-7k-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/gdgc9922pgc9sfe0n85c5shuv5dli9km/1671697575000/07254241957354570833/*/11LfmYHZBtwKLdaG39Vj29VJJCGLB6xn-?e=download&uuid=bb195c8f-8a1b-49fe-9d37-531549aca139
Resolving doc-0s-7k-docs.googleusercontent.com (doc-0s-7k-docs.googleusercontent.com)... 74.125.126.132, 2607:f8b0:4001:c1d::84
Connecting to doc-0s-7k-docs.googleusercontent.com (doc-0s-7k-docs.googleusercontent.com)|74.125.126.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2569 (2.5K) [text/csv]
Saving to: ‘carp_2022.csv’

carp_2022.csv       100%[===================>]   2.51K  --.-KB/s    in 0s

2022-12-22 08:26:22 (102 MB/s) - ‘carp_2022.csv’ saved [2569/2569]

In [2]:
import pandas as pd

df=pd.read_csv("carp_2022.csv",encoding="shift_jis")
df

,背番号,名前,登板,先発,救援,勝,負,S,H,防御率,...,故意四球,死球,対右被打数,対右被安打,対右奪三振,対右与四球,対左被打数,対左被安打,対左奪三振,対左与四球
0,11,九里亜蓮,26,24,2,6,9,0,0,3.33,...,3,8,261,69,70,23,275,78,51,30
1,12,大道温貴,3,3,0,0,1,0,0,6.75,...,0,1,23,9,4,0,25,7,4,3
2,13,森浦大輔,51,0,51,3,6,0,24,3.30,...,3,3,95,24,27,10,77,23,21,6
3,14,大瀬良大地,23,23,0,8,9,0,0,4.72,...,2,2,265,80,59,13,281,76,38,14
4,16,森翔平,8,2,6,1,0,0,1,1.89,...,0,1,37,12,5,3,37,10,5,5
5,18,森下暢仁,27,27,0,10,8,0,0,3.17,...,0,8,329,87,71,21,366,108,62,23
6,19,野村祐輔,9,9,0,2,3,0,0,5.23,...,1,0,83,32,8,8,87,23,10,6
7,20,栗林良吏,48,0,48,0,2,31,6,1.49,...,2,2,64,11,25,5,101,11,34,10
8,21,中崎翔太,28,0,28,2,5,0,7,6.46,...,3,1,39,11,3,2,53,16,15,8
9,23,薮田和樹,18,0,18,1,0,0,1,4.13,...,0,1,31,3,6,9,55,16,10,5
10,24,黒原拓未,12,0,12,0,0,0,1,6.52,...,0,1,19,5,6,1,20,6,5,3
11,28,床田寛樹,17,17,0,8,6,0,0,2.84,...,2,4,231,49,45,17,173,38,29,11
12,29,ケムナ誠,43,0,43,4,0,0,14,3.20,...,1,3,70,18,16,10,73,19,21,8
13,30,一岡竜司,10,0,10,1,0,0,1,2.08,...,0,0,19,9,5,0,21,6,2,1
14,36,塹江敦哉,26,0,26,3,2,0,6,3.12,...,1,1,21,8,3,3,38,5,5,5
15,39,菊池保則,8,0,8,0,0,0,2,5.63,...,1,1,18,6,3,4,15,4,3,0
16,41,矢崎拓也,47,0,47,2,0,1,17,1.82,...,1,0,88,20,21,11,88,15,30,14
17,42,アンダーソン,13,13,0,3,4,0,0,3.60,...,0,3,110,20,30,5,148,41,29,18
18,43,島内颯太郎,22,0,22,0,3,0,7,3.79,...,1,1,43,11,12,7,33,10,8,4
19,45,松本竜也,50,0,50,4,2,0,4,3.56,...,1,3,120,35,27,8,97,23,27,7
20,53,小林樹斗,1,0,1,0,0,0,0,9.00,...,0,0,2,0,0,1,2,2,0,0
21,58,藤井黎來,12,0,12,0,1,0,0,3.86,...,1,1,20,4,5,7,29,6,10,2
22,65,玉村昇悟,9,8,1,2,2,0,0,3.92,...,0,1,118,33,13,11,55,13,8,2
23,66,遠藤淳志,20,17,3,4,7,0,0,3.59,...,1,3,176,40,34,7,230,64,44,11
24,68,ターリー,45,0,45,2,4,0,14,3.11,...,2,2,55,14,13,8,76,12,19,8
25,97,フランスア,3,0,3,0,0,0,0,8.10,...,0,1,6,1,3,2,5,1,1,3
26,98,コルニエル,12,0,12,0,0,0,0,3.52,...,0,1,28,8,8,3,31,7,11,1

(1)先発登板数・救援登板数・勝利数が1以上の選手を, それぞれ多い順にソートした表を表示する.

In [3]:
df_s1 = df[df["先発"]>=1].sort_values('先発', ascending=False)
df_s1

,背番号,名前,登板,先発,救援,勝,負,S,H,防御率,...,故意四球,死球,対右被打数,対右被安打,対右奪三振,対右与四球,対左被打数,対左被安打,対左奪三振,対左与四球
5,18,森下暢仁,27,27,0,10,8,0,0,3.17,...,0,8,329,87,71,21,366,108,62,23
0,11,九里亜蓮,26,24,2,6,9,0,0,3.33,...,3,8,261,69,70,23,275,78,51,30
3,14,大瀬良大地,23,23,0,8,9,0,0,4.72,...,2,2,265,80,59,13,281,76,38,14
11,28,床田寛樹,17,17,0,8,6,0,0,2.84,...,2,4,231,49,45,17,173,38,29,11
23,66,遠藤淳志,20,17,3,4,7,0,0,3.59,...,1,3,176,40,34,7,230,64,44,11
17,42,アンダーソン,13,13,0,3,4,0,0,3.60,...,0,3,110,20,30,5,148,41,29,18
6,19,野村祐輔,9,9,0,2,3,0,0,5.23,...,1,0,83,32,8,8,87,23,10,6
22,65,玉村昇悟,9,8,1,2,2,0,0,3.92,...,0,1,118,33,13,11,55,13,8,2
1,12,大道温貴,3,3,0,0,1,0,0,6.75,...,0,1,23,9,4,0,25,7,4,3
4,16,森翔平,8,2,6,1,0,0,1,1.89,...,0,1,37,12,5,3,37,10,5,5

In [4]:
df_s2 = df[df["救援"]>=1].sort_values('救援', ascending=False)
df_s2

,背番号,名前,登板,先発,救援,勝,負,S,H,防御率,...,故意四球,死球,対右被打数,対右被安打,対右奪三振,対右与四球,対左被打数,対左被安打,対左奪三振,対左与四球
2,13,森浦大輔,51,0,51,3,6,0,24,3.30,...,3,3,95,24,27,10,77,23,21,6
19,45,松本竜也,50,0,50,4,2,0,4,3.56,...,1,3,120,35,27,8,97,23,27,7
7,20,栗林良吏,48,0,48,0,2,31,6,1.49,...,2,2,64,11,25,5,101,11,34,10
16,41,矢崎拓也,47,0,47,2,0,1,17,1.82,...,1,0,88,20,21,11,88,15,30,14
24,68,ターリー,45,0,45,2,4,0,14,3.11,...,2,2,55,14,13,8,76,12,19,8
12,29,ケムナ誠,43,0,43,4,0,0,14,3.20,...,1,3,70,18,16,10,73,19,21,8
8,21,中崎翔太,28,0,28,2,5,0,7,6.46,...,3,1,39,11,3,2,53,16,15,8
14,36,塹江敦哉,26,0,26,3,2,0,6,3.12,...,1,1,21,8,3,3,38,5,5,5
18,43,島内颯太郎,22,0,22,0,3,0,7,3.79,...,1,1,43,11,12,7,33,10,8,4
9,23,薮田和樹,18,0,18,1,0,0,1,4.13,...,0,1,31,3,6,9,55,16,10,5
26,98,コルニエル,12,0,12,0,0,0,0,3.52,...,0,1,28,8,8,3,31,7,11,1
21,58,藤井黎來,12,0,12,0,1,0,0,3.86,...,1,1,20,4,5,7,29,6,10,2
10,24,黒原拓未,12,0,12,0,0,0,1,6.52,...,0,1,19,5,6,1,20,6,5,3
13,30,一岡竜司,10,0,10,1,0,0,1,2.08,...,0,0,19,9,5,0,21,6,2,1
15,39,菊池保則,8,0,8,0,0,0,2,5.63,...,1,1,18,6,3,4,15,4,3,0
4,16,森翔平,8,2,6,1,0,0,1,1.89,...,0,1,37,12,5,3,37,10,5,5
23,66,遠藤淳志,20,17,3,4,7,0,0,3.59,...,1,3,176,40,34,7,230,64,44,11
25,97,フランスア,3,0,3,0,0,0,0,8.10,...,0,1,6,1,3,2,5,1,1,3
0,11,九里亜蓮,26,24,2,6,9,0,0,3.33,...,3,8,261,69,70,23,275,78,51,30
20,53,小林樹斗,1,0,1,0,0,0,0,9.00,...,0,0,2,0,0,1,2,2,0,0
22,65,玉村昇悟,9,8,1,2,2,0,0,3.92,...,0,1,118,33,13,11,55,13,8,2

In [5]:
df_s3 = df[df["勝"]>=1].sort_values('勝', ascending=False)
df_s3

,背番号,名前,登板,先発,救援,勝,負,S,H,防御率,...,故意四球,死球,対右被打数,対右被安打,対右奪三振,対右与四球,対左被打数,対左被安打,対左奪三振,対左与四球
5,18,森下暢仁,27,27,0,10,8,0,0,3.17,...,0,8,329,87,71,21,366,108,62,23
11,28,床田寛樹,17,17,0,8,6,0,0,2.84,...,2,4,231,49,45,17,173,38,29,11
3,14,大瀬良大地,23,23,0,8,9,0,0,4.72,...,2,2,265,80,59,13,281,76,38,14
0,11,九里亜蓮,26,24,2,6,9,0,0,3.33,...,3,8,261,69,70,23,275,78,51,30
23,66,遠藤淳志,20,17,3,4,7,0,0,3.59,...,1,3,176,40,34,7,230,64,44,11
19,45,松本竜也,50,0,50,4,2,0,4,3.56,...,1,3,120,35,27,8,97,23,27,7
12,29,ケムナ誠,43,0,43,4,0,0,14,3.20,...,1,3,70,18,16,10,73,19,21,8
2,13,森浦大輔,51,0,51,3,6,0,24,3.30,...,3,3,95,24,27,10,77,23,21,6
14,36,塹江敦哉,26,0,26,3,2,0,6,3.12,...,1,1,21,8,3,3,38,5,5,5
17,42,アンダーソン,13,13,0,3,4,0,0,3.60,...,0,3,110,20,30,5,148,41,29,18
8,21,中崎翔太,28,0,28,2,5,0,7,6.46,...,3,1,39,11,3,2,53,16,15,8
16,41,矢崎拓也,47,0,47,2,0,1,17,1.82,...,1,0,88,20,21,11,88,15,30,14
6,19,野村祐輔,9,9,0,2,3,0,0,5.23,...,1,0,83,32,8,8,87,23,10,6
22,65,玉村昇悟,9,8,1,2,2,0,0,3.92,...,0,1,118,33,13,11,55,13,8,2
24,68,ターリー,45,0,45,2,4,0,14,3.11,...,2,2,55,14,13,8,76,12,19,8
9,23,薮田和樹,18,0,18,1,0,0,1,4.13,...,0,1,31,3,6,9,55,16,10,5
13,30,一岡竜司,10,0,10,1,0,0,1,2.08,...,0,0,19,9,5,0,21,6,2,1
4,16,森翔平,8,2,6,1,0,0,1,1.89,...,0,1,37,12,5,3,37,10,5,5

(2)被打率(被安打/被打数)・被本塁打率(被本塁打*9/投球回)を計算し, 背番号・選手名と併記した表を表示する.

In [6]:
hit=df["被安打"]
atbat=df["対右被打数"]+df["対左被打数"]
home=df["被本塁打"]
inning=df["投球回"]

avg=hit/atbat
havg=home*9/inning

df2=df[["背番号","名前"]].copy()
df2["被打率"]=avg
df2["被本塁打率"]=havg
df2

    背番号      名前       被打率     被本塁打率
0    11    九里亜蓮  0.274254  0.833729
1    12    大道温貴  0.333333  3.750000
2    13    森浦大輔  0.273256  0.776978
3    14   大瀬良大地  0.285714  1.197044
4    16     森翔平  0.297297  0.473684
5    18    森下暢仁  0.280576  0.654851
6    19    野村祐輔  0.323529  0.870968
7    20    栗林良吏  0.133333  0.000000
8    21    中崎翔太  0.293478  2.281690
9    23    薮田和樹  0.220930  0.750000
10   24    黒原拓未  0.282051  0.000000
11   28    床田寛樹  0.215347  0.789474
12   29    ケムナ誠  0.258741  0.228814
13   30    一岡竜司  0.375000  0.000000
14   36    塹江敦哉  0.220339  0.519231
15   39    菊池保則  0.303030  2.250000
16   41    矢崎拓也  0.198864  0.364865
17   42  アンダーソン  0.236434  1.157143
18   43   島内颯太郎  0.276316  0.947368
19   45    松本竜也  0.267281  0.808383
20   53    小林樹斗  0.500000  0.000000
21   58    藤井黎來  0.204082  0.642857
22   65    玉村昇悟  0.265896  0.412214
23   66    遠藤淳志  0.256158  1.452532
24   68    ターリー  0.198473  1.672566
25   97   フランスア  0.181818  0.000000
26   98   コルニエル  0.254237  1.173913

(3)現役ドラフトで加入した戸根千明投手の, 今季の1軍成績を追加する.

In [7]:
df.loc[27]=[49,"戸根千明",9,0,9,0,0,0,0,5.02,14.3333,8,8,63,16,4,9,3,0,1,27,10,3,3,27,6,6,0]
df

,背番号,名前,登板,先発,救援,勝,負,S,H,防御率,...,故意四球,死球,対右被打数,対右被安打,対右奪三振,対右与四球,対左被打数,対左被安打,対左奪三振,対左与四球
0,11,九里亜蓮,26,24,2,6,9,0,0,3.33,...,3,8,261,69,70,23,275,78,51,30
1,12,大道温貴,3,3,0,0,1,0,0,6.75,...,0,1,23,9,4,0,25,7,4,3
2,13,森浦大輔,51,0,51,3,6,0,24,3.30,...,3,3,95,24,27,10,77,23,21,6
3,14,大瀬良大地,23,23,0,8,9,0,0,4.72,...,2,2,265,80,59,13,281,76,38,14
4,16,森翔平,8,2,6,1,0,0,1,1.89,...,0,1,37,12,5,3,37,10,5,5
5,18,森下暢仁,27,27,0,10,8,0,0,3.17,...,0,8,329,87,71,21,366,108,62,23
6,19,野村祐輔,9,9,0,2,3,0,0,5.23,...,1,0,83,32,8,8,87,23,10,6
7,20,栗林良吏,48,0,48,0,2,31,6,1.49,...,2,2,64,11,25,5,101,11,34,10
8,21,中崎翔太,28,0,28,2,5,0,7,6.46,...,3,1,39,11,3,2,53,16,15,8
9,23,薮田和樹,18,0,18,1,0,0,1,4.13,...,0,1,31,3,6,9,55,16,10,5
10,24,黒原拓未,12,0,12,0,0,0,1,6.52,...,0,1,19,5,6,1,20,6,5,3
11,28,床田寛樹,17,17,0,8,6,0,0,2.84,...,2,4,231,49,45,17,173,38,29,11
12,29,ケムナ誠,43,0,43,4,0,0,14,3.20,...,1,3,70,18,16,10,73,19,21,8
13,30,一岡竜司,10,0,10,1,0,0,1,2.08,...,0,0,19,9,5,0,21,6,2,1
14,36,塹江敦哉,26,0,26,3,2,0,6,3.12,...,1,1,21,8,3,3,38,5,5,5
15,39,菊池保則,8,0,8,0,0,0,2,5.63,...,1,1,18,6,3,4,15,4,3,0
16,41,矢崎拓也,47,0,47,2,0,1,17,1.82,...,1,0,88,20,21,11,88,15,30,14
17,42,アンダーソン,13,13,0,3,4,0,0,3.60,...,0,3,110,20,30,5,148,41,29,18
18,43,島内颯太郎,22,0,22,0,3,0,7,3.79,...,1,1,43,11,12,7,33,10,8,4
19,45,松本竜也,50,0,50,4,2,0,4,3.56,...,1,3,120,35,27,8,97,23,27,7
20,53,小林樹斗,1,0,1,0,0,0,0,9.00,...,0,0,2,0,0,1,2,2,0,0
21,58,藤井黎來,12,0,12,0,1,0,0,3.86,...,1,1,20,4,5,7,29,6,10,2
22,65,玉村昇悟,9,8,1,2,2,0,0,3.92,...,0,1,118,33,13,11,55,13,8,2
23,66,遠藤淳志,20,17,3,4,7,0,0,3.59,...,1,3,176,40,34,7,230,64,44,11
24,68,ターリー,45,0,45,2,4,0,14,3.11,...,2,2,55,14,13,8,76,12,19,8
25,97,フランスア,3,0,3,0,0,0,0,8.10,...,0,1,6,1,3,2,5,1,1,3
26,98,コルニエル,12,0,12,0,0,0,0,3.52,...,0,1,28,8,8,3,31,7,11,1
27,49,戸根千明,9,0,9,0,0,0,0,5.02,...,0,1,27,10,3,3,27,6,6,0

(4)対右・対左それぞれの被打率・K/BB(奪三振/与四球)を計算し, 被打率が小さい順にソートした表を表示する.

In [8]:
from re import L
ratbat=df["対右被打数"]
rhit=df["対右被安打"]
rk=df["対右奪三振"]
rbb=df["対右与四球"]
latbat=df["対左被打数"]
lhit=df["対左被安打"]
lk=df["対左奪三振"]
lbb=df["対左与四球"]

ravg=rhit/ratbat
rkbb=rk/rbb
lavg=lhit/latbat
lkbb=lk/lbb

df3=df[["背番号","名前"]].copy()
df3["対右被打率"]=ravg
df3["対右K/BB"]=rkbb
df3["対左被打率"]=lavg
df3["対左K/BB"]=lkbb

In [9]:
df3_s1 = df3.sort_values('対右被打率')
df3_s1

    背番号      名前     対右被打率    対右K/BB     対左被打率     対左K/BB
20   53    小林樹斗  0.000000  0.000000  1.000000        NaN
9    23    薮田和樹  0.096774  0.666667  0.290909   2.000000
25   97   フランスア  0.166667  1.500000  0.200000   0.333333
7    20    栗林良吏  0.171875  5.000000  0.108911   3.400000
17   42  アンダーソン  0.181818  6.000000  0.277027   1.611111
21   58    藤井黎來  0.200000  0.714286  0.206897   5.000000
11   28    床田寛樹  0.212121  2.647059  0.219653   2.636364
16   41    矢崎拓也  0.227273  1.909091  0.170455   2.142857
23   66    遠藤淳志  0.227273  4.857143  0.278261   4.000000
2    13    森浦大輔  0.252632  2.700000  0.298701   3.500000
24   68    ターリー  0.254545  1.625000  0.157895   2.375000
18   43   島内颯太郎  0.255814  1.714286  0.303030   2.000000
12   29    ケムナ誠  0.257143  1.600000  0.260274   2.625000
10   24    黒原拓未  0.263158  6.000000  0.300000   1.666667
0    11    九里亜蓮  0.264368  3.043478  0.283636   1.700000
5    18    森下暢仁  0.264438  3.380952  0.295082   2.695652
22   65    玉村昇悟  0.279661  1.181818  0.236364   4.000000
8    21    中崎翔太  0.282051  1.500000  0.301887   1.875000
26   98   コルニエル  0.285714  2.666667  0.225806  11.000000
19   45    松本竜也  0.291667  3.375000  0.237113   3.857143
3    14   大瀬良大地  0.301887  4.538462  0.270463   2.714286
4    16     森翔平  0.324324  1.666667  0.270270   1.000000
15   39    菊池保則  0.333333  0.750000  0.266667        inf
27   49    戸根千明  0.370370  1.000000  0.222222        inf
14   36    塹江敦哉  0.380952  1.000000  0.131579   1.000000
6    19    野村祐輔  0.385542  1.000000  0.264368   1.666667
1    12    大道温貴  0.391304       inf  0.280000   1.333333
13   30    一岡竜司  0.473684       inf  0.285714   2.000000

In [10]:
df3_s2 = df3.sort_values('対左被打率')
df3_s2

    背番号      名前     対右被打率    対右K/BB     対左被打率     対左K/BB
7    20    栗林良吏  0.171875  5.000000  0.108911   3.400000
14   36    塹江敦哉  0.380952  1.000000  0.131579   1.000000
24   68    ターリー  0.254545  1.625000  0.157895   2.375000
16   41    矢崎拓也  0.227273  1.909091  0.170455   2.142857
25   97   フランスア  0.166667  1.500000  0.200000   0.333333
21   58    藤井黎來  0.200000  0.714286  0.206897   5.000000
11   28    床田寛樹  0.212121  2.647059  0.219653   2.636364
27   49    戸根千明  0.370370  1.000000  0.222222        inf
26   98   コルニエル  0.285714  2.666667  0.225806  11.000000
22   65    玉村昇悟  0.279661  1.181818  0.236364   4.000000
19   45    松本竜也  0.291667  3.375000  0.237113   3.857143
12   29    ケムナ誠  0.257143  1.600000  0.260274   2.625000
6    19    野村祐輔  0.385542  1.000000  0.264368   1.666667
15   39    菊池保則  0.333333  0.750000  0.266667        inf
4    16     森翔平  0.324324  1.666667  0.270270   1.000000
3    14   大瀬良大地  0.301887  4.538462  0.270463   2.714286
17   42  アンダーソン  0.181818  6.000000  0.277027   1.611111
23   66    遠藤淳志  0.227273  4.857143  0.278261   4.000000
1    12    大道温貴  0.391304       inf  0.280000   1.333333
0    11    九里亜蓮  0.264368  3.043478  0.283636   1.700000
13   30    一岡竜司  0.473684       inf  0.285714   2.000000
9    23    薮田和樹  0.096774  0.666667  0.290909   2.000000
5    18    森下暢仁  0.264438  3.380952  0.295082   2.695652
2    13    森浦大輔  0.252632  2.700000  0.298701   3.500000
10   24    黒原拓未  0.263158  6.000000  0.300000   1.666667
8    21    中崎翔太  0.282051  1.500000  0.301887   1.875000
18   43   島内颯太郎  0.255814  1.714286  0.303030   2.000000
20   53    小林樹斗  0.000000  0.000000  1.000000        NaN

(5)今季三冠王を獲得した東京ヤクルトスワローズの村上宗隆選手に, 打率.340, 13本塁打, 26打点, OPS(出塁率+長打率)1.233と広島は特に打ち込まれた. 来季は村上選手に対してどのような対策を講じればよいか, 投手成績や村上選手の打者成績, その他のデータを基に考察する.

一般的には左打者に対し左投手をワンポイントで登板させるといった采配が行われるが, 今季の村上選手については, 対右打率.305, 対左打率.346と, 相手投手の右左関係なく好成績を残している.

そのため, 単に左投手を当てるのではなく, 左打者が比較的得意な投手 (勝ちパターン以外だと塹江・ターリー・戸根など) を当てることが必要だと考えた.

また, 今季村上選手を抑え込んだ栗林・大瀬良・野村の3投手を参考にすると, 左打者の内角に食い込む変化球 (右投手のスライダーやカットボール・左投手のシュートやツーシーム) を投げ切ることができる投手がより打たれないのではないかと考えた.

【参考サイト】

・スポーツナビ
https://baseball.yahoo.co.jp/npb/teams/6/memberlist?kind=p

・nf3 -Baseball Data House-
https://nf3.sakura.ne.jp/index.html

・aozora さん (Twitter)
https://twitter.com/aozora__nico2